project:
  type: website
  output-dir: docs

website:
  title: "MD & CH"
  site-url: "https://github.com/clfee/website"
  repo-url: "https://github.com/clfee/website"
  favicon: img/mi2.PNG
  page-navigation: false
  back-to-top-navigation: true
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2024  &middot; Made with r-project and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/clfee/website/
  
  navbar:
    background: "#F6F5F3"
    search: true
    title: false
    logo: img/mi_logo.png
    left:
      - href: index.qmd
        text: Home
      - gallery.qmd
      - about.qmd
      - contact.qmd
    tools:
      - icon: youtube
        href: https://youtube.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com

format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - img

editor: visual

