project:
  type: website

website:
  title: "MD & CH"
  site-url: "https://github.com/clfee/web"
  repo-url: "https://github.com/clfee/web"
  favicon: img/mi2.PNG
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2024  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/clfee/web/
  
  navbar:
    background: "#F6F5F3"
    search: true
    title: false
    logo: img/mi_logo.png
    left:
      - href: index.qmd
        text: Home
      - gallery.qmd
      - about.qmd
      - contact.qmd
    tools:
      - icon: youtube
        href: https://youtube.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

