project:
  type: website

website:
  title: "Chris Lee"
  description: "Data science applications brought to you by Chris Lee"
  site-url: "https://github.com/clfee/home"
  repo-url: "https://github.com/clfee"
  favicon: img/mi2.PNG
  image: img/cmm1.PNG
  open-graph: true
  page-navigation: false
  back-to-top-navigation: true
  search: true
  page-footer: 
    background: "#e0ddd6"
    center: © 2024  &middot; Made with r-project and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 

  
  navbar:
    background: "#fdfeff"
    search: true
    title: false
    logo: img/mi_logo_s.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "Demo"
        file: gallery.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/clfee
      - icon: rss
        href: index.xml

format:
  html:
    theme: my-litera.scss
    css: styles/custom.scss
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - img

editor: visual
 

