project:
  type: website
  output-dir: docs

website:
  title: "Chris Lee"
  site-url: "https://github.com/clfee/website"
  repo-url: "https://github.com/clfee/website"
  favicon: img/mi2.PNG
  page-navigation: false
  back-to-top-navigation: true
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2024  &middot; Made with r-project and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
  
  navbar:
    background: "#F6F5F3"
    search: true
    title: false
    logo: img/mi_logo.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: gallery.qmd
      - text: "About"
        file: about.qmd     
      - icon: github
        href: https://github.com/clfee

format:
  html:
    theme: 
      dark: zephyr
    css: styles/custom.scss
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - img

editor: visual

