---
title: "Demand Forecasting: Building a Base Model & Sharing through a Shiny App"
author:
    name: Chris Lee
    url: https://clfee.github.io/
date: 2025-02-025
format: 
  html:
        html-math-method: katex
        grid: 
            margin-width: 350px
fig-width: 8
fig-height: 6
editor_options: 
  chunk_output_type: console
execute: 
  echo: fenced
reference-location: margin
citation-location: margin
categories:
  - Shiny
  - Forecasting
preview: "cover_app.JPG"
---

## Overview

Forecasting has always been at the forefront of decision making and planning.

The uncertainty that surrounds the future is both exciting and challenging, with individuals and organizations seeking to minimize risks and maximize utilities. In the last article we completed an EDA of the sales data and discovered that promotions boosted sales in some but not all stores.Here we will forecast at the order_id crossed with center_id level.

We want to try a couple different models, including exponential smoothing(ets) and tbats from the forecast package and compare them against baseline models including naive, seasonal naive, and mean based forecasts. Ideally we will find a model type that performs best across all levels and can serve as our base model in production. Once we compare these models and find a base model, we can also look deeper into the results to try to build ideas for further improvement upon our base model.

The paper provides a detailed discussion of various forecasting methods, comparing them across different dimensions such as accuracy, complexity, and adaptability.

Classical statistical methods are based on time series modeling and statistical inference. Exponential Smoothing (ETS) and Autoregressive Integrated Moving Average (ARIMA) are commonly used as baselines in forecastingcompetitions.

Kaggle - [Food Demand Forecasting](https://www.kaggle.com/code/anoopashware/food-demand-forecasting-predict-orders).

